import type { CollectionConfig } from 'payload'

import { authenticated } from '../fields/access'

export const AnalyticsEvents: CollectionConfig = {
  slug: 'analytics-events',
  labels: { singular: 'Событие аналитики', plural: 'События аналитики' },
  access: { create: authenticated, delete: authenticated, read: authenticated, update: authenticated },
  admin: { hidden: true },
  timestamps: false,
  fields: [
    { name: 'eventId', type: 'text', required: true, unique: true, index: true, maxLength: 80 },
    { name: 'schemaVersion', type: 'number', required: true },
    { name: 'occurredAt', type: 'date', required: true, index: true },
    { name: 'receivedAt', type: 'date', required: true, index: true },
    { name: 'aggregatedAt', type: 'date', index: true },
    { name: 'anonymousId', type: 'text', required: true, index: true, maxLength: 80 },
    { name: 'sessionId', type: 'text', required: true, index: true, maxLength: 80 },
    { name: 'pageViewId', type: 'text', maxLength: 80 },
    { name: 'name', type: 'text', required: true, index: true, maxLength: 40 },
    { name: 'path', type: 'text', required: true, index: true, maxLength: 240 },
    { name: 'title', type: 'text', maxLength: 180 },
    { name: 'language', type: 'text', maxLength: 16 },
    { name: 'objectType', type: 'text', index: true, maxLength: 24 },
    { name: 'objectId', type: 'text', index: true, maxLength: 160 },
    { name: 'actionKind', type: 'text', index: true, maxLength: 24 },
    { name: 'formType', type: 'text', index: true, maxLength: 40 },
    { name: 'step', type: 'number' },
    { name: 'value', type: 'number' },
    { name: 'metricName', type: 'text', maxLength: 8 },
    { name: 'consentState', type: 'text', required: true, maxLength: 20 },
    { name: 'channel', type: 'text', index: true, maxLength: 40 },
    { name: 'source', type: 'text', maxLength: 80 },
    { name: 'medium', type: 'text', maxLength: 80 },
    { name: 'campaign', type: 'text', index: true, maxLength: 120 },
    { name: 'content', type: 'text', maxLength: 120 },
    { name: 'term', type: 'text', maxLength: 120 },
    { name: 'referrerDomain', type: 'text', index: true, maxLength: 160 },
    { name: 'clickIdType', type: 'text', maxLength: 16 },
    { name: 'clickId', type: 'text', maxLength: 180 },
    { name: 'firstChannel', type: 'text', maxLength: 40 },
    { name: 'firstSource', type: 'text', maxLength: 80 },
    { name: 'firstMedium', type: 'text', maxLength: 80 },
    { name: 'firstCampaign', type: 'text', maxLength: 120 },
    { name: 'device', type: 'text', index: true, maxLength: 20 },
    { name: 'browser', type: 'text', maxLength: 30 },
    { name: 'os', type: 'text', maxLength: 30 },
    { name: 'osVersion', type: 'text', maxLength: 30 },
    { name: 'isBot', type: 'checkbox', defaultValue: false },
    { name: 'lead', type: 'relationship', relationTo: 'leads', index: true },
  ],
}
